# Generated by Django 5.2.9 on 2026-01-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Konum'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Kilitli mi?'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Sabitli mi?'),
        ),
    ]
