# Generated by Django 5.2.9 on 2026-01-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_profile_location_topic_is_closed_topic_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
