# Generated by Django 5.2.9 on 2026-01-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_privatemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Free', 'Ücretsiz Üye'), ('Premium', 'Premium Üye'), ('Expert', 'Uzman')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Kilitli'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Sabitlenmiş'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
