# Generated by Django 5.2.9 on 2026-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_privatemessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_on_private_message',
            field=models.BooleanField(default=True, verbose_name='Özel mesaj geldiğinde email gönder'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_reply',
            field=models.BooleanField(default=True, verbose_name='Konuma cevap geldiğinde email gönder'),
        ),
    ]
