# Generated by Django 5.2.9 on 2026-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_profile_email_on_private_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_best_answer',
            field=models.BooleanField(default=False, verbose_name='En Faydalı Yanıt'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Beğeni Sayısı'),
        ),
    ]
