# Generated by Django 5.2.9 on 2026-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Akademik Puan'),
        ),
    ]
