# Generated by Django 5.2.9 on 2026-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_profile_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rozet Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('icon', models.CharField(default='bi-award', max_length=50, verbose_name='İkon (Bootstrap Icons)')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Renk (Hex)')),
                ('badge_type', models.CharField(choices=[('achievement', 'Başarı'), ('specialty', 'Uzmanlık'), ('participation', 'Katılım'), ('special', 'Özel')], default='achievement', max_length=20)),
                ('points_required', models.IntegerField(default=0, verbose_name='Gereken Puan (0=manuel)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['-points_required'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('newbie', 'Çaylak'), ('member', 'Üye'), ('active', 'Aktif Üye'), ('contributor', 'Katkıcı'), ('expert', 'Uzman'), ('master', 'Usta'), ('legend', 'Efsane'), ('admin', 'Yönetici')], default='newbie', max_length=20, verbose_name='Rütbe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='forum.badge', verbose_name='Rozetler'),
        ),
    ]
