# Generated by Django 5.2.9 on 2026-01-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_badge_profile_rank_profile_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Yetenek Adı')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-lightbulb', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Renk')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Akademik Unvan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='best_answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='En İyi Cevap Sayısı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='GitHub Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_scholar',
            field=models.URLField(blank=True, default='', verbose_name='Google Scholar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Profil Herkese Açık'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ORCID ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Email Adresini Göster'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_likes_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Alınan Beğeni'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Gönderi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_topics',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Konu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Twitter/X Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Üniversite'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Web Sitesi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='forum.skill', verbose_name='Uzmanlık Alanları'),
        ),
    ]
