# Generated by Django 5.2.9 on 2026-01-17 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('category', models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('excel', 'Excel'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji'), ('academic', 'Akademik Yazım')], max_length=20, verbose_name='Kategori')),
                ('icon', models.CharField(default='bi-lightbulb', max_length=50, verbose_name='İkon')),
                ('publish_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Beğeni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Günlük İpucu',
                'verbose_name_plural': 'Günlük İpuçları',
                'ordering': ['-publish_date'],
            },
        ),
    ]
