# Generated by Django 5.2.9 on 2026-01-17 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_dailytip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Soru')),
                ('option_a', models.CharField(max_length=255, verbose_name='A Şıkkı')),
                ('option_b', models.CharField(max_length=255, verbose_name='B Şıkkı')),
                ('option_c', models.CharField(max_length=255, verbose_name='C Şıkkı')),
                ('option_d', models.CharField(max_length=255, verbose_name='D Şıkkı')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Cevap')),
                ('category', models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji')], max_length=20, verbose_name='Kategori')),
                ('difficulty', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='medium', max_length=10, verbose_name='Zorluk')),
                ('explanation', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz Sorusu',
                'verbose_name_plural': 'Quiz Soruları',
            },
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Toplam Puan')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Doğru Cevap')),
                ('total_answers', models.PositiveIntegerField(default=0, verbose_name='Toplam Cevap')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Seri')),
                ('last_played', models.DateTimeField(blank=True, null=True, verbose_name='Son Oynanma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Puanı',
                'verbose_name_plural': 'Quiz Puanları',
            },
        ),
    ]
